//! # bayan-ffi
//!
//! The C ABI of the engine, for the desktop shell.
//!
//! The desktop shell (C++ and Qt) calls the engine through a small C interface whose header is generated by cbindgen ([ADR-0012]). This crate will be that thin binding around bayan-engine. It is built for the desktop platforms only, not for WebAssembly (the web uses bayan-wasm).
//!
//! **Unsafe code.** Talking to C requires `unsafe` code, so this is one of the two crates where it is not forbidden ([ADR-0006] §2). It is still denied by default: it is allowed only where `#[expect(unsafe_code, reason = "…")]` marks it, every `unsafe` block carries a `// SAFETY:` comment explaining why it is sound, and no panic may cross into C (ADR-0006 §4).
//!
//! **Status:** an empty skeleton created by CORE-001. Its implementation arrives with work package [CORE-007].
//!
//! ## Layer
//!
//! bayan-ffi belongs to the **Bindings and tools** layer.
//!
//! bayan-core's crates are arranged in layers, from lowest to highest: Foundation → Model and formats → Text → Layout → Output → Interaction → Engine → Bindings and tools. **A crate may depend only on crates in its own layer or below; lower layers never know about higher ones.** This keeps the engine testable and lets the server reuse the lower crates it needs without the layout engine ([architecture §4][architecture]). bayan-ffi may therefore depend on crates of every layer and on external libraries.
//!
//! [CORE-007]: https://github.com/BayanDocs/docs/blob/HEAD/workpackages/phase-0/CORE-007-engine-skeleton.md
//! [architecture]: https://github.com/BayanDocs/docs/blob/HEAD/plan/03-architecture.md#4-inside-bayan-core
//! [ADR-0012]: https://github.com/BayanDocs/docs/blob/HEAD/adr/0012-engine-boundary.md
//! [ADR-0006]: https://github.com/BayanDocs/docs/blob/HEAD/adr/0006-rust-core-and-memory-safety.md
