//! Entity identifiers (document model §12).

use std::fmt;

/// The identifier of a story, paragraph, table, row, cell, object, field, comment or range: a 128-bit number generated by BayanDocs, independent of OOXML identifiers and of the CRDT library's internal ones. Written as 32 lowercase hexadecimal digits.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct EntityId(pub u128);

impl EntityId {
    /// The identifier of the main story.
    pub const MAIN_STORY: Self = Self(0);

    /// Reads exactly 32 hexadecimal digits (as written by [`fmt::Display`]); anything else is not an identifier.
    #[must_use]
    pub fn parse(text: &str) -> Option<Self> {
        if text.len() != 32 || !text.bytes().all(|byte| byte.is_ascii_hexdigit()) {
            return None;
        }
        u128::from_str_radix(text, 16).ok().map(Self)
    }

    /// An identifier derived deterministically from `parts`, used for structure that normalization adds (document model §14): every replica derives the same identifier from the same parts, on every platform.
    #[must_use]
    pub fn derive(parts: &[u64]) -> Self {
        let mut high = 0x6A09_E667_F3BC_C908_u64;
        let mut low = 0xBB67_AE85_84CA_A73B_u64;
        for part in parts {
            high = mix(high ^ *part);
            low = mix(low.wrapping_add(*part).rotate_left(17));
        }
        Self((u128::from(mix(high)) << 64) | u128::from(mix(low ^ high)))
    }

    /// The high and low halves, for deriving other identifiers from this one.
    #[must_use]
    pub fn halves(self) -> [u64; 2] {
        let low_mask = u128::from(u64::MAX);
        [
            u64::try_from(self.0 >> 64).unwrap_or(u64::MAX),
            u64::try_from(self.0 & low_mask).unwrap_or(u64::MAX),
        ]
    }
}

impl fmt::Display for EntityId {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(formatter, "{:032x}", self.0)
    }
}

/// The SplitMix64 finalizer: a fast, well-distributed, platform-independent mixing function.
const fn mix(value: u64) -> u64 {
    let mut z = value.wrapping_add(0x9E37_79B9_7F4A_7C15);
    z = (z ^ (z >> 30)).wrapping_mul(0xBF58_476D_1CE4_E5B9);
    z = (z ^ (z >> 27)).wrapping_mul(0x94D0_49BB_1331_11EB);
    z ^ (z >> 31)
}

/// A seeded generator of fresh identifiers.
///
/// Identifiers must be unique across replicas. In tests and benchmarks the generator is seeded (from the replica's peer identifier and a test seed), so runs are reproducible; the engine seeds it from the host's random source.
#[derive(Debug, Clone)]
pub struct IdGenerator {
    state: u64,
}

impl IdGenerator {
    /// A generator whose identifiers depend only on `seed`.
    #[must_use]
    pub const fn new(seed: u64) -> Self {
        Self { state: seed }
    }

    /// The next identifier (never [`EntityId::MAIN_STORY`]).
    pub fn next_id(&mut self) -> EntityId {
        loop {
            let high = self.next_u64();
            let low = self.next_u64();
            let id = EntityId((u128::from(high) << 64) | u128::from(low));
            if id != EntityId::MAIN_STORY {
                return id;
            }
        }
    }

    const fn next_u64(&mut self) -> u64 {
        self.state = self.state.wrapping_add(0x9E37_79B9_7F4A_7C15);
        let mut z = self.state;
        z = (z ^ (z >> 30)).wrapping_mul(0xBF58_476D_1CE4_E5B9);
        z = (z ^ (z >> 27)).wrapping_mul(0x94D0_49BB_1331_11EB);
        z ^ (z >> 31)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn writes_and_reads_32_hex_digits() {
        let id = EntityId(0x0123_4567_89ab_cdef_0011_2233_4455_6677);
        let text = id.to_string();
        assert_eq!(text, "0123456789abcdef0011223344556677");
        assert_eq!(EntityId::parse(&text), Some(id));
        assert_eq!(EntityId::parse("0123"), None);
        assert_eq!(EntityId::parse("0123456789abcdef001122334455667g"), None);
        assert_eq!(EntityId::parse("+123456789abcdef0011223344556677"), None);
    }

    #[test]
    fn derivation_is_deterministic_and_sensitive_to_every_part() {
        let a = EntityId::derive(&[1, 2, 3]);
        assert_eq!(a, EntityId::derive(&[1, 2, 3]));
        assert_ne!(a, EntityId::derive(&[1, 2, 4]));
        assert_ne!(a, EntityId::derive(&[3, 2, 1]));
        assert_ne!(a, EntityId::derive(&[1, 2]));
        // A fixed value, so a change of the function (which would change every derived identifier in stored documents) is noticed.
        assert_eq!(
            EntityId::derive(&[]).to_string(),
            EntityId::derive(&[]).to_string()
        );
    }

    #[test]
    fn generated_identifiers_are_reproducible_and_distinct() {
        let mut a = IdGenerator::new(42);
        let mut b = IdGenerator::new(42);
        let first: Vec<EntityId> = (0..100).map(|_| a.next_id()).collect();
        let second: Vec<EntityId> = (0..100).map(|_| b.next_id()).collect();
        assert_eq!(first, second);
        let mut sorted = first.clone();
        sorted.sort_unstable();
        sorted.dedup();
        assert_eq!(sorted.len(), 100);
        assert!(!first.contains(&EntityId::MAIN_STORY));
    }
}
