/*
 * bayan_ffi.h: the C interface between a BayanDocs shell and the engine (engine protocol v0, docs repository: specs/engine-protocol.md §3.1).
 *
 * Rules for callers:
 * - All JSON is UTF-8 and is passed with an explicit length; it is not NUL-terminated.
 * - Pointers passed to the engine are borrowed only for the duration of the call.
 * - The engine runs on its own thread and calls the message callback on that thread, one message at a time.
 * - The json pointer given to the callback is valid only during the call: copy the bytes and hand them to your own thread.
 * - Never call an engine synchronously from inside a callback (spec §8): bayan_render_tile returns
 *   BAYAN_STATUS_WRONG_THREAD inside any engine's callback, because it would wait for the thread it runs on, or for
 *   another engine that may be waiting for this one. Posting from the callback is allowed.
 * - Every function may be called from any thread, also from several threads at once, except bayan_engine_free:
 *   it must be the last call on an engine, made when no thread other than the engine's own callback is inside a
 *   call on that engine.
 *   It stops the engine; after it returns, the callback is never called again.
 * - No function lets a Rust panic escape; failures are reported through return values and engine.error messages.
 *   The callback must not let a C++ exception escape either.
 * - Panics inside the engine are not printed, because their messages could quote document content: the first
 *   bayan_engine_new installs a Rust panic hook that stays silent for the engine's threads and calls, and hands
 *   every other panic in the process to the hook installed before.
 *
 * SPDX-FileCopyrightText: 2026 BayanDocs contributors
 * SPDX-License-Identifier: GPL-3.0-or-later WITH LicenseRef-BayanDocs-App-Store-Permission
 */

#ifndef BAYAN_FFI_H
#define BAYAN_FFI_H

/* Generated by cbindgen from crates/bayan-ffi/src/lib.rs; do not edit. Regenerate with: BAYAN_UPDATE_GENERATED=1 cargo test -p bayan-ffi --test header */

#include <stddef.h>
#include <stdint.h>

/*
 An engine instance. Opaque: only pointers to it exist outside the engine.
 */
typedef struct BayanEngine BayanEngine;

/*
 The result of a call.
 */
typedef int32_t BayanStatus;

/*
 Receives one message from the engine (a reply or an event, as UTF-8 JSON of `json_len` bytes), on the engine thread. `json` is valid only during the call.
 */
typedef void (*BayanMessageCallback)(void *user_data, const uint8_t *json, size_t json_len);

/*
 Identifies a blob (bulk bytes kept by the engine, such as file contents). 0 is never a valid blob.
 */
typedef uint64_t BayanBlobId;

/*
 The call succeeded.
 */
#define BAYAN_STATUS_OK 0

/*
 A null pointer, a malformed request, or a size outside the engine's limits (spec §13).
 */
#define BAYAN_STATUS_INVALID_ARGUMENT 1

/*
 An unknown blob, document or page.
 */
#define BAYAN_STATUS_NOT_FOUND 2

/*
 The output buffer is too small; the function says how to learn the size needed.
 */
#define BAYAN_STATUS_BUFFER_TOO_SMALL 3

/*
 The engine failed or is stopping; it also reports an engine.error message when it can.
 */
#define BAYAN_STATUS_INTERNAL_ERROR 4

/*
 Called from inside the engine's callback, where the function would wait for the engine thread it runs on (spec §8).
 */
#define BAYAN_STATUS_WRONG_THREAD 5

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/*
 Returns the engine's semantic version, as a static NUL-terminated string.
 */
const char *bayan_version(void);

/*
 Creates an engine from a JSON configuration object of `config_len` bytes (spec §3.3); a null pointer with length 0 means the defaults. Starts the engine thread. Returns NULL if the configuration is invalid or the thread cannot start.

 # Safety

 Unless `config_len` is 0, `config_json` must point to `config_len` readable bytes.
 */
BayanEngine *bayan_engine_new(const uint8_t *config_json,
                              size_t config_len);

/*
 Stops and destroys an engine; accepts NULL. Called from any other thread, it waits until the engine thread has stopped; meanwhile the callback may still be running, and if it calls `bayan_engine_post` that call fails with `BAYAN_STATUS_INTERNAL_ERROR`. Called from inside the engine's own callback, it returns at once and the engine thread finishes by itself. Either way, the callback is never called again after this returns.

 # Safety

 `engine` must be NULL or a pointer that `bayan_engine_new` returned and that was not freed yet. This must be the last call on the engine: apart from the engine's own callback, no other thread may be inside a call on it (a callback that frees the engine must first make sure of that), and the engine must not be used afterwards.
 */
void bayan_engine_free(BayanEngine *engine);

/*
 Registers the message callback, before the first `bayan_engine_post`: a later registration replaces an earlier one until then, and once a message has been posted every call returns `BAYAN_STATUS_INVALID_ARGUMENT`. `user_data` is passed back unchanged and must be usable from the engine thread.

 # Safety

 `engine` must be a live engine. `callback` must be safe to call on the engine thread with `user_data` until the engine is freed.
 */
BayanStatus bayan_engine_set_callback(BayanEngine *engine,
                                      BayanMessageCallback callback,
                                      void *user_data);

/*
 Queues one message (a protocol envelope of `json_len` bytes of UTF-8 JSON, spec §4) for the engine thread and returns without waiting for it to be handled. Returns `BAYAN_STATUS_INVALID_ARGUMENT` for a null pointer, an empty message or one over 16 MiB, and `BAYAN_STATUS_INTERNAL_ERROR` if the engine is stopping.

 # Safety

 `engine` must be a live engine, and `json` must point to `json_len` readable bytes.
 */
BayanStatus bayan_engine_post(BayanEngine *engine,
                              const uint8_t *json,
                              size_t json_len);

/*
 Copies `len` bytes into a new blob and returns its identifier, or 0 if `engine` is NULL, `bytes` is NULL while `len` is not 0, the blob is larger than 64 MiB, or there are too many blobs (spec §13). An empty blob is allowed; then `bytes` may be NULL.

 # Safety

 `engine` must be a live engine, and unless `len` is 0, `bytes` must point to `len` readable bytes.
 */
BayanBlobId bayan_blob_put(BayanEngine *engine,
                           const uint8_t *bytes,
                           size_t len);

/*
 Copies a blob's bytes into `out`, which has room for `out_capacity` bytes, and sets `*out_len` to the blob's size. If the blob does not fit (a NULL `out` has room for nothing), returns `BAYAN_STATUS_BUFFER_TOO_SMALL` and still sets `*out_len`, so callers can ask for the size first with `out` NULL; an empty blob always fits, so asking for its size returns `BAYAN_STATUS_OK`. Returns `BAYAN_STATUS_NOT_FOUND` for an unknown blob.

 # Safety

 `engine` must be a live engine, `out_len` must point to a writable `size_t`, and unless `out` is NULL, it must point to `out_capacity` writable bytes.
 */
BayanStatus bayan_blob_get(BayanEngine *engine,
                           BayanBlobId blob,
                           uint8_t *out,
                           size_t out_capacity,
                           size_t *out_len);

/*
 Releases a blob. Returns `BAYAN_STATUS_NOT_FOUND` if it did not exist.

 # Safety

 `engine` must be a live engine.
 */
BayanStatus bayan_blob_release(BayanEngine *engine, BayanBlobId blob);

/*
 Renders a tile into a caller-provided buffer of premultiplied RGBA8 pixels, rows from top to bottom, and returns when it is done (spec §3.1, §6.4).

 - `request_json`: a `render.tile` payload of `request_len` bytes: `doc_id`, `page`, `rect` (x, y, width and height in BLU), and optionally `zoom`, `device_scale` and `mode`. If it has `width` and `height`, they must equal the parameters.
 - `width`, `height`: the tile's size in pixels, 1 to 4,096 each.
 - `stride`: the distance between the starts of two rows, in bytes; at least 4 × `width`. The bytes between rows are left untouched.
 - `out_capacity`: the size of `rgba_out` in bytes; at least `stride` × (`height` − 1) + 4 × `width`, otherwise `BAYAN_STATUS_BUFFER_TOO_SMALL`.

 The request is handled on the engine thread in order with the posted messages, so it waits for messages posted before it. From inside any engine's callback it returns `BAYAN_STATUS_WRONG_THREAD`, because waiting there could deadlock.

 # Safety

 `engine` must be a live engine, `request_json` must point to `request_len` readable bytes, and `rgba_out` to `out_capacity` writable bytes that nothing else uses during the call.
 */
BayanStatus bayan_render_tile(BayanEngine *engine,
                              const uint8_t *request_json,
                              size_t request_len,
                              uint8_t *rgba_out,
                              size_t out_capacity,
                              uint32_t width,
                              uint32_t height,
                              size_t stride);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* BAYAN_FFI_H */
