// TypeScript declarations of the BayanDocs engine protocol, version 0 (docs repository: specs/engine-protocol.md).
// Generated by bayan-engine from the JSON Schema of the engine's Rust types (engine-protocol.schema.json); do not edit.
// They describe the messages as the web shell exchanges them with the worker host: blob fields hold ArrayBuffers, and the
// reply to render.tile carries an ImageBitmap (specification §3.2). Version 0 is unstable and may change between core releases.

/** The protocol version these declarations describe. */
export type ProtocolVersion = 0;

/** The payloads of the messages the shell sends, by message type. */
export interface Requests {
  "hello": Hello;
  "doc.open": DocOpen;
  "doc.close": DocClose;
  "view.set": ViewSet;
  "render.tile": RenderTile;
  "input.pointer": InputPointer;
  "input.key": InputKey;
  "input.text": InputText;
  "input.composition": InputComposition;
  "query.a11y": QueryA11y;
  "ui.manifest": UiManifestRequest;
  "diag.record.start": Empty;
  "diag.record.stop": Empty;
  "diag.replay": DiagReplay;
  "diag.panic": Empty;
}

/** The payloads of successful replies, by the type of the request they answer. */
export interface Replies {
  "hello": Welcome;
  "doc.open": DocOpened;
  "doc.close": Empty;
  "view.set": Empty;
  "render.tile": RenderTileWebReply;
  "input.pointer": Empty;
  "input.key": Empty;
  "input.text": Empty;
  "input.composition": Empty;
  "query.a11y": A11yTree;
  "ui.manifest": UiManifest;
  "diag.record.start": Empty;
  "diag.record.stop": RecordStopped;
  "diag.replay": ReplayReport;
  "diag.panic": Empty;
}

/** The payloads of the events the engine sends, by event type. */
export interface Events {
  "view.layout.progress": ViewLayoutProgress;
  "view.pages": ViewPages;
  "render.invalidate": RenderInvalidate;
  "overlay.update": OverlayUpdate;
  "a11y.update": A11yUpdate;
  "engine.error": EngineError;
}

/** The types of the messages the shell sends. */
export type RequestType = keyof Requests;

/** The types of the events the engine sends. */
export type EventType = keyof Events;

/** A message from the shell to the engine (spec §4). Without `id`, the engine sends no reply. */
export type EngineRequest<T extends RequestType = RequestType> = {
  [K in T]: { v: ProtocolVersion; id?: number; type: K; payload: Requests[K] };
}[T];

/** A successful reply to a request of type `T` (spec §4). */
export interface EngineReplyOk<T extends RequestType = RequestType> {
  v: ProtocolVersion;
  re: number;
  ok: true;
  /** The reply's name, where the specification gives one (`welcome`, `doc.opened`). */
  type?: string;
  payload: Replies[T];
}

/** A failed reply (spec §4). */
export interface EngineReplyError {
  v: ProtocolVersion;
  re: number;
  ok: false;
  error: ErrorInfo;
}

/** The reply to a request of type `T`. */
export type EngineReply<T extends RequestType = RequestType> = EngineReplyOk<T> | EngineReplyError;

/** An event from the engine (spec §4). */
export type EngineEvent<T extends EventType = EventType> = {
  [K in T]: { v: ProtocolVersion; type: K; seq: number; payload: Events[K] };
}[T];

/** Any message from the engine. */
export type EngineMessage = EngineReply | EngineEvent;

/** The engine configuration (spec §3.3). */
export interface EngineConfig {
  test?: {
    /** Lets `diag.panic` make the engine panic, for tests of the error path. */
    allow_panic?: boolean;
  };
}

/** The worker host's first message from the main thread, optional (spec §3.2). */
export interface WorkerInit {
  worker: "init";
  config?: EngineConfig;
  /** The address of bayan_wasm_bg.wasm, resolved against the worker script's address. */
  wasm_url?: string;
}

/** The worker host is ready. */
export interface WorkerReady {
  worker: "ready";
  engine_version: string;
}

/**
 * The worker host stopped working, and ignores every later message: the configuration is invalid (`invalid_config`), the
 * engine module could not be loaded (`load_failed`), or the engine could not be replaced after a panic (`restart_failed`).
 */
export interface WorkerFailed {
  worker: "failed";
  reason: "invalid_config" | "load_failed" | "restart_failed";
}

/** A control message from the worker host. */
export type WorkerStatus = WorkerReady | WorkerFailed;

/** The accessibility caret: a position in a node's text. */
export interface A11yCaret {
  /** The node. */
  node: number;
  /** The position, in UTF-16 code units into the node's text. */
  offset: number;
}

/** One change to the accessibility tree. */
export interface A11yChange {
  /** What changed. */
  kind: A11yChangeKind;
  /** The new version of the node, children included. */
  node: A11yNode;
}

/** The kind of an accessibility change. */
export type A11yChangeKind = "replace";

/** A node of the accessibility tree. */
export interface A11yNode {
  /** The node's box. */
  bounds?: PageRect | null;
  /** The box of every character of `text`, on the page of `bounds`. */
  chars?: CharBox[] | null;
  /** The node's children, in reading order. */
  children?: A11yNode[] | null;
  /** Whether the user can edit the node's text. */
  editable?: boolean;
  /** The node's identifier, stable for its lifetime. */
  id: number;
  /** A heading's level, 1 to 9. */
  level?: number | null;
  /** An accessible name where the content does not provide one. */
  name?: string | null;
  /** The node's role. */
  role: A11yRole;
  /** The node's own text, on nodes that hold text. */
  text?: string | null;
}

/** The role of an accessibility node. */
export type A11yRole = "document" | "heading" | "paragraph" | "list" | "list_item" | "table" | "row" | "column_header" | "cell";

/** The reply to `query.a11y`. */
export interface A11yTree {
  /** The accessibility caret, or `null`. */
  caret: A11yCaret | null;
  /** The document. */
  doc_id: number;
  /** The requested subtree. */
  root: A11yNode;
}

/** `a11y.update`: changes to the accessibility tree. */
export interface A11yUpdate {
  /** The accessibility caret, or `null`. */
  caret: A11yCaret | null;
  /** The changes, in order. */
  changes: A11yChange[];
  /** The document. */
  doc_id: number;
}

/** One value in the `args` of an error or warning: only codes and numbers, never document content (spec §12). */
export type ArgValue = string | number | boolean | number[];

/** A blob: bulk bytes kept outside the JSON (spec §3). On the C interface, its identifier, a positive integer; on the web, the bytes themselves as an `ArrayBuffer` (spec §3.2). */
export type BlobRef = ArrayBuffer;

/** What the shell can do. */
export interface Capabilities {
  /** Whether the shell bridges the accessibility tree to the platform. */
  accessibility?: boolean;
  /** The clipboard formats the shell can exchange, as MIME types. */
  clipboard_formats?: string[];
  /** Whether the shell forwards input-method composition. */
  ime?: boolean;
}

/** The caret. */
export interface Caret {
  /** The page it is on. */
  page: number;
  /** Its rectangle, in page coordinates. */
  rect: Rect;
  /** Whether the shell should show it. */
  visible: boolean;
}

/** The box of one character. */
export interface CharBox {
  /** The code unit after the character. */
  end: number;
  /** The character's box, in page coordinates. */
  rect: Rect;
  /** The character's first UTF-16 code unit in the node's text. */
  start: number;
}

/** The phase of an input method composition. */
export type CompositionPhase = "start" | "update" | "end";

/** `diag.replay`: replays a recording. */
export interface DiagReplay {
  /** The recording. */
  blob: BlobRef;
}

/** `doc.close`: closes a document. */
export interface DocClose {
  /** The document. */
  doc_id: number;
}

/** `doc.open`: opens a document from a blob. */
export interface DocOpen {
  /** The document's bytes. The v0 skeleton opens the mock document whatever they contain. */
  blob: BlobRef;
  /** The file name, for format detection and display only; never logged. */
  file_name_hint?: string | null;
  /** The format, if the shell knows it, such as `docx`. */
  format_hint?: string | null;
}

/** `doc.opened`: the reply to `doc.open`. */
export interface DocOpened {
  /** The new document's identifier. */
  doc_id: number;
  /** Fonts the document asks for that are missing. */
  fonts: FontReport;
  /** How many pages the document is expected to have. */
  page_count_estimate: number;
  /** Problems found while opening, as Fluent messages. */
  warnings: Warning[];
}

/** A payload without fields: the payload of requests that need none, and the reply to requests that only succeed or fail. */
export type Empty = Record<string, never>;

/** `engine.error`: an error without a request to answer, or a panic (spec §12). */
export interface EngineError {
  /** Codes and numbers that explain the error; never document content. */
  args: { [key: string]: ArgValue };
  /** What went wrong, for programs. */
  code: ErrorCode;
  /** A Fluent message identifier, for people. */
  message_id: string;
  /** `true`: the engine kept its state. `false`: it discarded its session, and the shell starts a new one with `hello`. */
  recoverable: boolean;
}

/** What went wrong (spec §12). */
export type ErrorCode = "invalid_message" | "unsupported_protocol_version" | "handshake_required" | "unsupported_message" | "invalid_request" | "not_found" | "limit_exceeded" | "already_recording" | "not_recording" | "invalid_recording" | "recording_mismatch" | "not_allowed" | "panic" | "internal";

/** The error of a failed reply (spec §4). */
export interface ErrorInfo {
  /** Codes and numbers that explain the error; never document content. */
  args: { [key: string]: ArgValue };
  /** What went wrong, for programs. */
  code: ErrorCode;
  /** A Fluent message identifier, for people. */
  message_id: string;
}

/** Fonts a document asks for that the engine does not have. */
export interface FontReport {
  /** Whether the layout depends on a font found only among the user's installed fonts (ADR-0004 §3). */
  machine_dependent: boolean;
  /** The missing font families. */
  missing: string[];
}

/** `hello`: the shell starts a session (spec §5). */
export interface Hello {
  /** What the shell can do. */
  capabilities?: Capabilities | null;
  /** The interface language, as a BCP 47 tag. */
  locale?: string | null;
  /** The protocol versions the shell speaks; must contain 0. */
  protocol_versions: number[];
  /** Which shell this is. */
  shell?: ShellInfo | null;
  /** The interface theme, such as `light` or `dark`. */
  theme?: string | null;
}

/** An `ImageBitmap` transferred from the web worker (spec §3.2); only in the TypeScript declarations. */
export type ImageBitmapRef = ImageBitmap;

/** `input.composition`: input method composition (pre-edit text). */
export interface InputComposition {
  /** The document. */
  doc_id: number;
  /** What happened. */
  phase: CompositionPhase;
  /** The input method's caret or selection within `text`. */
  selection?: TextRange | null;
  /** The composition's text (for `update`). */
  text?: string;
}

/** `input.key`: a key press. */
export interface InputKey {
  /** The physical key, as the DOM's `KeyboardEvent.code`, such as `KeyA`. */
  code?: string;
  /** Whether an input method composition owns the key; the engine then ignores it. */
  composing?: boolean;
  /** The document. */
  doc_id: number;
  /** The key's meaning, as the DOM's `KeyboardEvent.key`, such as `Backspace` or `ArrowLeft`. */
  key: string;
  /** The modifier keys held. */
  modifiers?: Modifiers;
  /** Whether the key repeats because it is held down. */
  repeat?: boolean;
}

/** `input.pointer`: a mouse, pen or touch event. */
export interface InputPointer {
  /** The button, numbered as the DOM's `button`: 0 is the primary button. */
  button?: number;
  /** The click count: 2 for a double click. */
  clicks?: number;
  /** The document. */
  doc_id: number;
  /** What happened. */
  kind: PointerKind;
  /** The modifier keys held. */
  modifiers?: Modifiers;
  /** The kind of pointer. */
  pointer_type?: PointerType | null;
  /** The horizontal position, in device-independent pixels from the view origin. */
  x: number;
  /** The vertical position, in device-independent pixels from the view origin. */
  y: number;
}

/** `input.text`: committed text. */
export interface InputText {
  /** The document. */
  doc_id: number;
  /** The text, inserted at the caret. */
  text: string;
}

/** The modifier keys held during an input event. */
export interface Modifiers {
  /** Alt (Option on macOS). */
  alt?: boolean;
  /** Control. */
  ctrl?: boolean;
  /** Meta (Command on macOS, the Windows key on Windows). */
  meta?: boolean;
  /** Shift. */
  shift?: boolean;
}

/** `overlay.update`: what the shell draws over the tiles (spec §6.3). */
export interface OverlayUpdate {
  /** The caret, or `null` when there is none. */
  caret: Caret | null;
  /** The document. */
  doc_id: number;
  /** Find highlights (Phase 2); always empty in v0. */
  highlights: unknown[];
  /** Other people's cursors (Phase 3); always empty in v0. */
  remote: unknown[];
  /** The selection's rectangles, per page. */
  selection: SelectionRects[];
}

/** One page of `view.pages`. */
export interface PageInfo {
  /** The page's height. */
  height: number;
  /** The page's index, counting from 0. */
  index: number;
  /** The index of the page's section. */
  section: number;
  /** The page's width. */
  width: number;
  /** The page's left edge in view space. */
  x: number;
  /** The page's top edge in view space. */
  y: number;
}

/** A rectangle on a page, in that page's coordinates. */
export interface PageRect {
  /** The page's index, counting from 0. */
  page: number;
  /** The rectangle, in BLU from the page's top-left corner. */
  rect: Rect;
}

/** What a pointer did. */
export type PointerKind = "down" | "move" | "up" | "cancel";

/** The kind of pointer. */
export type PointerType = "mouse" | "pen" | "touch";

/** `query.a11y`: asks for the accessibility tree. */
export interface QueryA11y {
  /** The document. */
  doc_id: number;
  /** The node whose subtree to return; the whole document when omitted. */
  node?: number | null;
}

/** The reply to `diag.record.stop`. */
export interface RecordStopped {
  /** The recording (spec §10), as a blob that the shell releases. */
  blob: BlobRef;
  /** The number of entries. */
  entries: number;
  /** Whether a limit stopped the recording early. */
  truncated: boolean;
}

/** A rectangle in BLU (1/25,400 point, ADR-0005). */
export interface Rect {
  /** The height; positive. */
  height: number;
  /** The width; positive. */
  width: number;
  /** The left edge. */
  x: number;
  /** The top edge. */
  y: number;
}

/** `render.invalidate`: parts of pages whose tiles the shell must request again. */
export interface RenderInvalidate {
  /** The document. */
  doc_id: number;
  /** The changed regions, in page coordinates. */
  regions: PageRect[];
}

/** Which rasterizer renders a tile (ADR-0011 §2–§3). */
export type RenderMode = "reference" | "interactive";

/** `render.tile`: asks for the pixels of part of a page (spec §6.4). */
export interface RenderTile {
  /** Physical pixels per device-independent pixel, a hint for later rasterizers; it does not change the pixels. */
  device_scale?: number | null;
  /** The document. */
  doc_id: number;
  /** The tile's height in pixels, 1 to 4,096. Required in the message form; on the C interface, `bayan_render_tile`'s parameter gives it. */
  height?: number | null;
  /** The rasterizer to use (ADR-0011 §3); both give the same pixels in v0. */
  mode?: RenderMode | null;
  /** The page's index. */
  page: number;
  /** The part of the page, in page coordinates. */
  rect: Rect;
  /** The tile's width in pixels, 1 to 4,096. Required in the message form; on the C interface, `bayan_render_tile`'s parameter gives it. */
  width?: number | null;
  /** The zoom factor, a hint for later rasterizers; it does not change the pixels. */
  zoom?: number | null;
}

/** The reply to `render.tile` in the message form, on the C interface. */
export interface RenderTileReply {
  /** The pixels, premultiplied RGBA8, rows from top to bottom, as a blob that the shell releases. */
  blob: BlobRef;
  /** The digest of the pixels, `fnv1a64:` and 16 hexadecimal digits (spec §10). */
  hash: string;
  /** The tile's height in pixels. */
  height: number;
  /** Bytes from the start of one row to the next: 4 × width. */
  stride: number;
  /** The tile's width in pixels. */
  width: number;
}

/** The reply to `render.tile` as the web worker host delivers it (spec §3.2): the pixels as an `ImageBitmap`. This type exists for the TypeScript declarations; no JSON has this shape. */
export interface RenderTileWebReply {
  /** The pixels. */
  bitmap: ImageBitmapRef;
  /** The digest of the engine's premultiplied pixels (spec §10). */
  hash: string;
  /** The tile's height in pixels. */
  height: number;
  /** The tile's width in pixels. */
  width: number;
}

/** The reply to `diag.replay`. */
export interface ReplayReport {
  /** The number of entries replayed. */
  entries: number;
  /** The index of the first entry that did not, or `null`. */
  first_difference: number | null;
  /** Whether every entry produced exactly what it produced when it was recorded. */
  identical: boolean;
  /** Every tile rendered during the replay. */
  tiles: ReplayTile[];
}

/** A tile rendered during a replay. */
export interface ReplayTile {
  /** The index of the entry that rendered it. */
  entry: number;
  /** The digest of the pixels (spec §10). */
  hash: string;
  /** The height in pixels. */
  height: number;
  /** The page. */
  page: number;
  /** The width in pixels. */
  width: number;
}

/** Selection rectangles on one page. */
export interface SelectionRects {
  /** The page. */
  page: number;
  /** The rectangles, in page coordinates. */
  rects: Rect[];
}

/** Which shell started the session. */
export interface ShellInfo {
  /** The shell's name, such as `bayan-desktop`. */
  name?: string;
  /** The operating system or browser it runs on. */
  platform?: string;
  /** The shell's version. */
  version?: string;
}

/** A range of UTF-16 code units. */
export interface TextRange {
  /** The code unit after the last one; equal to `start` for an empty range (a caret). */
  end: number;
  /** The first code unit. */
  start: number;
}

/** A command of the UI manifest. */
export interface UiCommand {
  /** The command's identifier, such as `format.bold.toggle`. */
  id: string;
  /** Its label, formatted. */
  label: string;
  /** Its default shortcut, such as `Ctrl+B`. */
  shortcut?: string | null;
}

/** A group of a ribbon tab. */
export interface UiGroup {
  /** The identifiers of its commands, in order. */
  commands: string[];
  /** The group's identifier. */
  id: string;
  /** Its label, formatted. */
  label: string;
}

/** The UI manifest: a stub in v0 (spec §6.8). */
export interface UiManifest {
  /** The commands. */
  commands: UiCommand[];
  /** The language of the strings. */
  locale: string;
  /** The manifest format's version: 0. */
  manifest_version: number;
  /** The ribbon. */
  ribbon: UiRibbon;
}

/** `ui.manifest`: asks for the UI manifest. */
export interface UiManifestRequest {
  /** The language of the strings, as a BCP 47 tag. */
  locale?: string | null;
}

/** The ribbon. */
export interface UiRibbon {
  /** The tabs, in order. */
  tabs: UiTab[];
}

/** A ribbon tab. */
export interface UiTab {
  /** Its groups, in order. */
  groups: UiGroup[];
  /** The tab's identifier. */
  id: string;
  /** Its label, formatted. */
  label: string;
}

/** `view.layout.progress`: how far layout has come. */
export interface ViewLayoutProgress {
  /** Whether layout is complete. */
  complete: boolean;
  /** The document. */
  doc_id: number;
  /** How many pages the document is expected to have. */
  page_count_estimate: number;
  /** The number of pages laid out so far. */
  pages_laid_out: number;
}

/** How pages are shown. */
export type ViewMode = "print" | "web" | "draft" | "focus";

/** `view.pages`: the document's pages and where they sit in view space (spec §7). */
export interface ViewPages {
  /** The document. */
  doc_id: number;
  /** The pages, in order. */
  pages: PageInfo[];
}

/** `view.set`: tells the engine what the shell shows. */
export interface ViewSet {
  /** Physical pixels per device-independent pixel. */
  device_scale: number;
  /** The document. */
  doc_id: number;
  /** The view mode. */
  mode: ViewMode;
  /** Whether to show paragraph marks and other formatting marks. */
  show_formatting_marks?: boolean;
  /** The visible part of the page area, in device-independent pixels from the view origin. */
  viewport: Viewport;
  /** The zoom factor: 1 shows a document at its real size. */
  zoom: number;
}

/** A rectangle in device-independent pixels. */
export interface Viewport {
  /** The height. */
  height: number;
  /** The width. */
  width: number;
  /** The left edge. */
  x: number;
  /** The top edge. */
  y: number;
}

/** A problem found while opening a document. */
export interface Warning {
  /** Codes and numbers for the message. */
  args: { [key: string]: ArgValue };
  /** A Fluent message identifier. */
  message_id: string;
}

/** `welcome`: the reply to `hello`. */
export interface Welcome {
  /** The core's semantic version. */
  engine_version: string;
  /** What this engine offers, such as `mock_document`. */
  features: string[];
  /** The layout epoch (ADR-0004 §4). */
  layout_epoch: number;
  /** The protocol version of the session: 0. */
  protocol_version: number;
}
