//! # bayan-wasm
//!
//! The WebAssembly binding of the engine and its Web Worker host, for the web shell.
//!
//! The web shell runs the engine as WebAssembly inside a Web Worker and exchanges protocol messages with it ([engine protocol specification][protocol-spec] §3.2, [ADR-0012], [ADR-0014]). This crate is the thin binding around bayan-engine that wasm-bindgen turns into a WebAssembly module and its JavaScript glue: [`WasmEngine`] hands JSON messages to an [`Engine`] and returns its answers, and keeps the engine's blobs. The worker host, `js/bayan-worker.js`, is plain JavaScript without dependencies: it relays messages between the web shell and the engine, turns blobs into `ArrayBuffer`s and tiles into `ImageBitmap`s, and replaces the engine when it panics. `js/test-page.html` is a page for trying the worker by hand. `cargo xtask wasm-package` builds the package, which also contains the protocol's JSON Schema and TypeScript declarations.
//!
//! A browser gives WebAssembly no threads of its own here, so the engine runs inside the worker, one message at a time, and never blocks: the worker host is the engine thread of the web (spec §8). The worker host passes the time a message arrived; the engine reads no clock (ADR-0005).
//!
//! **Panics.** WebAssembly in a browser cannot unwind, so a panic stops the module's instance (it traps). The worker host catches the trap, makes wasm-bindgen create a fresh instance, and lets a new [`WasmEngine`] report the panic with [`WasmEngine::report_panic`] (spec §3.2, ADR-0006 §4). Native hosts never see this: there [`Engine::handle`] catches panics itself.
//!
//! **Unsafe code.** The JavaScript boundary needs `unsafe` code, so this is one of the two crates where it is not forbidden ([ADR-0006] §2). It is still denied by default, and this crate has none of its own: the unsafe code that crosses the boundary is generated by wasm-bindgen's `#[wasm_bindgen]` attribute, which the dependency review of wasm-bindgen covers (ADR-0017). Unsafe code added here must be allowed with `#[expect(unsafe_code, reason = "…")]`, and a comment above every `unsafe` block must explain why it is sound.
//!
//! ## Layer
//!
//! bayan-wasm belongs to the **Bindings and tools** layer.
//!
//! bayan-core's crates are arranged in layers, from lowest to highest: Foundation → Model and formats → Text → Layout → Output → Interaction → Engine → Bindings and tools. **A crate may depend only on crates in its own layer or below; lower layers never know about higher ones.** This keeps the engine testable and lets the server reuse the lower crates it needs without the layout engine ([architecture §4][architecture]). bayan-wasm may therefore depend on crates of every layer and on external libraries.
//!
//! [architecture]: https://github.com/BayanDocs/docs/blob/HEAD/plan/03-architecture.md#4-inside-bayan-core
//! [protocol-spec]: https://github.com/BayanDocs/docs/blob/HEAD/specs/engine-protocol.md
//! [ADR-0012]: https://github.com/BayanDocs/docs/blob/HEAD/adr/0012-engine-boundary.md
//! [ADR-0014]: https://github.com/BayanDocs/docs/blob/HEAD/adr/0014-web-shell.md
//! [ADR-0006]: https://github.com/BayanDocs/docs/blob/HEAD/adr/0006-rust-core-and-memory-safety.md

use std::sync::Arc;

use bayan_engine::blobs::{BlobId, BlobStore};
use bayan_engine::config::Config;
use bayan_engine::limits::{MAX_BLOB_BYTES, MAX_ID, MAX_MESSAGE_BYTES};
use bayan_engine::{ENGINE_VERSION, Engine};
use wasm_bindgen::prelude::wasm_bindgen;

/// The largest blob identifier, 2⁵³ − 1, as the JavaScript number that holds it exactly.
const MAX_ID_NUMBER: f64 = 9_007_199_254_740_991.0;

/// The engine's semantic version.
#[wasm_bindgen(js_name = engineVersion)]
#[must_use]
pub fn engine_version() -> String {
    ENGINE_VERSION.to_owned()
}

/// The largest blob in bytes (spec §13). The worker host refuses a larger `ArrayBuffer` before copying it into the module's memory.
#[wasm_bindgen(js_name = maxBlobBytes)]
#[must_use]
pub fn max_blob_bytes() -> u32 {
    u32::try_from(MAX_BLOB_BYTES).unwrap_or(u32::MAX)
}

/// The longest message in bytes of UTF-8 JSON (spec §13). The worker host answers a longer message with [`WasmEngine::refuse_oversized`] instead of copying it into the module's memory.
#[wasm_bindgen(js_name = maxMessageBytes)]
#[must_use]
pub fn max_message_bytes() -> u32 {
    u32::try_from(MAX_MESSAGE_BYTES).unwrap_or(u32::MAX)
}

/// An engine inside the worker.
#[wasm_bindgen]
pub struct WasmEngine {
    engine: Engine,
}

#[wasm_bindgen]
impl WasmEngine {
    /// Creates an engine from its configuration, a JSON object as text (spec §3.3); an empty string means the defaults.
    ///
    /// # Errors
    ///
    /// Throws the string `invalid_config` if the configuration is not valid; the reason never repeats the configuration's content.
    #[wasm_bindgen(constructor)]
    pub fn new(config_json: &str) -> Result<WasmEngine, String> {
        let config =
            Config::from_json(config_json.as_bytes()).map_err(|_| "invalid_config".to_owned())?;
        Ok(Self {
            engine: Engine::new(config, Arc::new(BlobStore::new())),
        })
    }

    /// Handles one message, a protocol envelope as JSON text (spec §4), that arrived `received_ms` milliseconds after the worker started, and returns the engine's answers as the text of a JSON array, in order.
    ///
    /// A panic traps: the call throws, and this engine and every other object of the module's instance must not be used again (see the crate documentation).
    #[must_use]
    pub fn post(&mut self, message_json: &str, received_ms: f64) -> String {
        json_array(
            &self
                .engine
                .handle(message_json.as_bytes(), milliseconds(received_ms)),
        )
    }

    /// On a new engine: the answers that report that the engine before it panicked while handling `message_json` (spec §3.2), as the text of a JSON array.
    #[wasm_bindgen(js_name = reportPanic)]
    #[must_use]
    pub fn report_panic(&mut self, message_json: &str) -> String {
        json_array(&self.engine.report_panic(message_json.as_bytes()))
    }

    /// The answer to `message_json` when the worker host could not deliver the engine's reply, for example because the browser could not create a tile's `ImageBitmap` (spec §3.2), as the text of a JSON array.
    #[wasm_bindgen(js_name = reportHostFailure)]
    #[must_use]
    pub fn report_host_failure(&mut self, message_json: &str) -> String {
        json_array(&self.engine.report_host_failure(message_json.as_bytes()))
    }

    /// The answer to a message the worker host did not hand to the engine because it is longer than [`max_message_bytes`]: `limit_exceeded` as the reply to request `id`, or, if `id` is not a request identifier (pass `NaN` when the message has none), as `engine.error` (spec §3.2, §13). Returns the text of a JSON array.
    #[wasm_bindgen(js_name = refuseOversized)]
    #[must_use]
    pub fn refuse_oversized(&mut self, id: f64) -> String {
        json_array(&self.engine.refuse_oversized(identifier(id)))
    }

    /// Stores bytes from the shell in a new blob and returns its identifier, or 0 if a limit refuses them (spec §13). The engine answers a message that names blob 0 with `limit_exceeded`.
    #[wasm_bindgen(js_name = blobPut)]
    #[must_use]
    pub fn blob_put(&mut self, bytes: &[u8]) -> f64 {
        self.engine
            .blobs()
            .put_shell(bytes)
            .map_or(0.0, identifier_number)
    }

    /// Returns a blob's bytes and releases it, or `undefined` if there is no such blob.
    #[wasm_bindgen(js_name = blobTake)]
    #[must_use]
    pub fn blob_take(&mut self, blob: f64) -> Option<Vec<u8>> {
        let bytes = self.engine.blobs().take(identifier(blob)?)?;
        Some(bytes.to_vec())
    }

    /// Releases a blob. Returns whether it existed.
    #[wasm_bindgen(js_name = blobRelease)]
    pub fn blob_release(&mut self, blob: f64) -> bool {
        identifier(blob).is_some_and(|id| self.engine.blobs().release(id))
    }
}

/// The engine's messages as one JSON array, so the worker host parses them with a single `JSON.parse`. Each message is already a JSON object.
fn json_array(messages: &[String]) -> String {
    let mut array = String::with_capacity(
        messages
            .iter()
            .map(|message| message.len() + 1)
            .sum::<usize>()
            + 2,
    );
    array.push('[');
    for (index, message) in messages.iter().enumerate() {
        if index > 0 {
            array.push(',');
        }
        array.push_str(message);
    }
    array.push(']');
    array
}

/// A time from the worker host, in whole milliseconds. `performance.now()` gives fractions, which the engine does not need.
#[expect(
    clippy::cast_possible_truncation,
    clippy::cast_sign_loss,
    reason = "a float-to-integer `as` cast saturates: fractions are cut off, negative numbers and NaN become 0, and numbers beyond u64 become u64::MAX, all harmless for a recording's timestamps"
)]
fn milliseconds(value: f64) -> u64 {
    value as u64
}

/// A blob identifier from JavaScript: a whole number from 1 to 2⁵³ − 1, which a JavaScript number holds exactly (spec §4).
#[expect(
    clippy::cast_possible_truncation,
    clippy::cast_sign_loss,
    reason = "the value was just checked to be a whole number from 1 to 2^53 - 1, which converts exactly"
)]
fn identifier(value: f64) -> Option<BlobId> {
    let whole = value.trunc() == value;
    (whole && (1.0..=MAX_ID_NUMBER).contains(&value)).then_some(value as BlobId)
}

/// A blob identifier as a JavaScript number.
#[expect(
    clippy::cast_precision_loss,
    reason = "blob identifiers are at most 2^53 - 1 (the blob store refuses larger ones), which an f64 holds exactly"
)]
fn identifier_number(id: BlobId) -> f64 {
    debug_assert!(id <= MAX_ID, "blob identifiers stay below 2^53");
    id as f64
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::Value;

    fn parse(text: &str) -> Vec<Value> {
        serde_json::from_str(text).unwrap()
    }

    #[test]
    fn the_largest_identifier_is_2_to_the_53_minus_1() {
        assert_eq!(MAX_ID, 9_007_199_254_740_991);
        assert_eq!(identifier(MAX_ID_NUMBER), Some(MAX_ID));
    }

    #[test]
    fn only_whole_numbers_in_range_are_blob_identifiers() {
        assert_eq!(identifier(1.0), Some(1));
        assert_eq!(identifier(2.0), Some(2));
        for refused in [
            0.0,
            -0.0,
            -1.0,
            0.5,
            1.5,
            f64::NAN,
            f64::INFINITY,
            f64::NEG_INFINITY,
            9_007_199_254_740_992.0,
        ] {
            assert_eq!(identifier(refused), None, "{refused}");
        }
        assert_eq!(identifier_number(7), 7.0);
    }

    #[test]
    fn times_are_whole_milliseconds() {
        assert_eq!(milliseconds(12.9), 12);
        assert_eq!(milliseconds(-3.0), 0);
        assert_eq!(milliseconds(f64::NAN), 0);
        assert_eq!(milliseconds(f64::INFINITY), u64::MAX);
    }

    #[test]
    fn invalid_configurations_are_refused_without_their_content() {
        assert!(WasmEngine::new("").is_ok());
        assert!(WasmEngine::new(r#"{"test":{"allow_panic":true}}"#).is_ok());
        for invalid in ["[", r#"{"test":{"secret_switch":true}}"#] {
            assert_eq!(
                WasmEngine::new(invalid).err().as_deref(),
                Some("invalid_config")
            );
        }
    }

    #[test]
    fn messages_and_blobs_round_trip_through_the_binding() {
        let mut engine = WasmEngine::new("").unwrap();
        let welcome = parse(&engine.post(
            r#"{"v":0,"id":1,"type":"hello","payload":{"protocol_versions":[0]}}"#,
            0.0,
        ));
        assert_eq!(welcome[0]["type"], "welcome");
        let blob = engine.blob_put(b"document");
        assert_eq!(blob, 1.0);
        let opened = parse(&engine.post(
            &format!(r#"{{"v":0,"id":2,"type":"doc.open","payload":{{"blob":{blob}}}}}"#),
            1.0,
        ));
        assert_eq!(opened[0]["type"], "doc.opened");
        assert!(engine.blob_release(blob));
        assert!(!engine.blob_release(blob));
        let doc_id = &opened[0]["payload"]["doc_id"];
        let tile = parse(&engine.post(
            &format!(
                r#"{{"v":0,"id":3,"type":"render.tile","payload":{{"doc_id":{doc_id},"page":0,"rect":{{"x":0,"y":0,"width":1905000,"height":1905000}},"width":8,"height":8}}}}"#
            ),
            2.5,
        ));
        let reply = &tile[0]["payload"];
        let pixels = engine.blob_take(reply["blob"].as_f64().unwrap()).unwrap();
        assert_eq!(pixels.len(), 8 * 8 * 4);
        assert_eq!(reply["hash"], bayan_engine::digest::of_bytes(&pixels));
        // Taking releases the blob.
        assert_eq!(engine.blob_take(reply["blob"].as_f64().unwrap()), None);
        assert_eq!(engine.blob_take(f64::NAN), None);
    }

    #[test]
    fn a_blob_over_the_limit_is_refused_with_identifier_0() {
        let mut engine = WasmEngine::new("").unwrap();
        let limit = usize::try_from(max_blob_bytes()).unwrap();
        assert_eq!(limit, MAX_BLOB_BYTES);
        assert_eq!(engine.blob_put(&vec![0; limit + 1]), 0.0);
    }

    #[test]
    fn a_new_engine_reports_the_panic_and_host_failures() {
        let mut engine = WasmEngine::new("").unwrap();
        let panic = parse(&engine.report_panic(r#"{"v":0,"id":5,"type":"diag.panic"}"#));
        assert_eq!(panic.len(), 2);
        assert_eq!(panic[0]["re"], 5);
        assert_eq!(panic[0]["error"]["code"], "panic");
        assert_eq!(panic[1]["payload"]["recoverable"], false);
        let oversized = parse(&engine.refuse_oversized(9.0));
        assert_eq!(oversized[0]["re"], 9);
        assert_eq!(oversized[0]["error"]["args"]["limit"], "message_size");
        let anonymous = parse(&engine.refuse_oversized(f64::NAN));
        assert_eq!(anonymous[0]["type"], "engine.error");
        assert_eq!(max_message_bytes(), 16 * 1024 * 1024);
        let failure = parse(&engine.report_host_failure(r#"{"v":0,"id":6,"type":"render.tile"}"#));
        assert_eq!(failure.len(), 1);
        assert_eq!(failure[0]["error"]["code"], "internal");
        assert_eq!(json_array(&[]), "[]");
    }
}
